// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-09. Record: docs/decisions/0015-hooks.md.
export default function hooks(body = {}) {
  return { "pre-commit": { "checks": body.hooks?.preCommit ?? [], "lint-staged": "pnpm lint-staged --concurrent false --no-stash --no-revert" } };
}
