// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-11. Record: docs/decisions/0014-lint-staged.md.
export default function lintStaged(body = {}) {
  return { "*.{cjs,js,jsx,mjs,ts,tsx}": ["prettier --check", "eslint --max-warnings=0 --no-warn-ignored", "secretlint --no-glob"], "*.{css,json,md,yaml,yml}": ["prettier --check"] };
}
