// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-11. Record: docs/decisions/0007-prettier.md.
export default function prettier(body = {}) {
  return { "endOfLine": "auto" };
}
