// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-10. Record: docs/decisions/0008-secretlint.md.
export default function secretlint(body = {}) {
  return { "rules": [{ "id": "@secretlint/secretlint-rule-preset-recommend" }] };
}
