// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-11. Record: docs/decisions/0013-syncpack.md.
export default function syncpack(body = {}) {
  return { "versionGroups": [{ "dependencies": body.workspacePackages ?? [], "dependencyTypes": ["prod", "dev"], "packages": ["**"], "pinVersion": "workspace:*" }, { "dependencies": body.floatingPeers ?? [], "dependencyTypes": ["peer"], "isIgnored": true }] };
}
