// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-10. Record: docs/decisions/0013-syncpack.md.
export default function syncpack(body = {}) {
  return { "versionGroups": { "floatingPeers": { "dependencies": body.floatingPeers ?? [], "dependencyTypes": ["peer"], "isIgnored": true }, "workspace": { "dependencies": body.workspacePackages ?? [], "dependencyTypes": ["prod", "dev"], "packages": ["**"], "pinVersion": "workspace:*" } } };
}
