export const RECORD_NUMBERS = { eslint: 4, tsconfig: 5, stylelint: 6, prettier: 7, secretlint: 8, jscpd: 9, cspell: 10, "ls-lint": 11, knip: 12, syncpack: 13, "lint-staged": 14, hooks: 15 };

const TESTS = ["agree", "adopt", "strictest", "consistency", "benefit", "parameter", "inert", "residue"];
const cell = (v) => (v === null || v === undefined ? "—" : "`" + JSON.stringify(v).replaceAll("|", "\\|") + "`");
const pad = (n) => String(n).padStart(4, "0");

export function renderRecord({ number, tool, rows, provenance }) {
  const counts = Object.fromEntries(TESTS.map((t) => [t, rows.filter((r) => r.test === t).length]));
  const lines = [];
  lines.push(`# ADR ${pad(number)} — ${tool} reconciliation`);
  lines.push("");
  lines.push(`**Date:** ${provenance.date}`);
  lines.push("**Status:** accepted");
  lines.push("**Spec:** docs/specs/2026-09-08-phase-2b-reconciliation-design.md");
  lines.push(`**Generated by:** \`orrery reconcile\` from ${provenance.a.name} \`${provenance.a.sha}\` and ${provenance.b.name} \`${provenance.b.sha}\`. Do not edit by hand; re-run and re-commit.`);
  lines.push("");
  lines.push("Ruling order: stricter wins; if strictness is undefined, the more consistent option; then the option that benefits the code most. Project data is a parameter. `a` is " + provenance.a.name + ", `b` is " + provenance.b.name + ".");
  lines.push("");
  if (tool === "eslint") {
    lines.push("| surface | " + provenance.a.name + " sample | " + provenance.b.name + " sample |");
    lines.push("|---|---|---|");
    for (const s of Object.keys(provenance.a.samples)) lines.push(`| ${s} | \`${provenance.a.samples[s]}\` | \`${provenance.b.samples[s] ?? "—"}\` |`);
    lines.push("");
  }
  lines.push("| test | rows |");
  lines.push("|---|---|");
  for (const t of TESTS) lines.push(`| ${t} | ${counts[t]} |`);
  lines.push("");
  const surfaces = [...new Set(rows.map((r) => r.surface))];
  for (const surface of surfaces) {
    const table = rows.filter((r) => r.surface === surface && r.test !== "inert" && r.test !== "residue");
    if (table.length === 0) continue;
    lines.push(`## ${surface}`);
    lines.push("");
    lines.push(`| key | ${provenance.a.name} | ${provenance.b.name} | ruling | test | tier | note |`);
    lines.push("|---|---|---|---|---|---|---|");
    for (const r of table) lines.push(`| \`${r.key}\` | ${cell(r.a)} | ${cell(r.b)} | ${cell(r.chosen)} | ${r.test} | ${r.tier ?? "—"} | ${r.note} |`);
    lines.push("");
  }
  const inert = rows.filter((r) => r.test === "inert");
  if (inert.length) {
    lines.push("## Inert (off on one side, absent on the other)");
    lines.push("");
    lines.push("Behaviourally identical to absent on both sides; not emitted into the bundle.");
    lines.push("");
    for (const surface of surfaces) {
      const list = inert.filter((r) => r.surface === surface);
      if (list.length) lines.push(`- **${surface}:** ` + list.map((r) => "`" + r.key + "`").join(", "));
    }
    lines.push("");
  }
  const residue = rows.filter((r) => r.test === "residue");
  if (residue.length) {
    lines.push("## Residue — needs a ruling");
    lines.push("");
    for (const r of residue) lines.push(`- ${r.surface} \`${r.key}\`: ${provenance.a.name} ${cell(r.a)}, ${provenance.b.name} ${cell(r.b)} — ${r.note}`);
    lines.push("");
  }
  return lines.join("\n");
}
