// GENERATED by orrery reconcile from aeleos 5e70a21 and libra 1c79de72 on 2026-09-10. Record: docs/decisions/0012-knip.md.
export default function knip(body = {}) {
  return { "apps": { "entry": ["src/app/**/*.{ts,tsx}", "src/features/*/index.ts", "tests/**/*.{ts,tsx}", ...(body.knip?.apps?.extraEntries ?? [])], "project": ["tests/**/*.{ts,tsx}", ...(body.knip?.apps?.extraProjects ?? [])] }, "packages": { "entry": ["tests/**/*.{ts,tsx}", ...(body.knip?.packages?.extraEntries ?? [])], "project": [...(body.knip?.packages?.extraProjects ?? [])] }, "root": body.knip?.root ?? {} };
}
